### ISSUE TITLE
testes

### ISSUE THREAD

**Issue by felipequecole** [felipequecole/DC-UFSCar-ES2-201701--Grupo-Depende#4]
Inserção de item bibliográfico (bibtex entry), para as categorias book e
article.
– Acessível via BibTeX → New entry
– Alguns detalhes da funcionalidade podem ser vistos em
<http://help.jabref.org/en/EntryEditorHelp>
 Importação de itens bibliográficos na base corrente
– Acessível via File → Import into current database

**Comment by WellitonAlt** [comment]
Adicionado a classe ArtigoTeste e LivroTeste que testam a inserção nos text box fora do padrão desejado.
